import type { Metadata } from "next";
import BootstrapClient from "./components/BootstrapClient";
import MusicPlayerProvider from "./state/playerProvider";
import Header from "./components/Header/Header";
import Player from "./components/Player/Player";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { PrimeReactProvider } from "primereact/api";
import "primereact/resources/themes/lara-light-cyan/theme.css";
import "primeicons/primeicons.css";
import UserAuthProvider, { UserAuthContext } from "./state/userAuthProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className="min-vh-100 d-flex flex-column"
        style={{
          backgroundColor: "#d6d8e7",
          maxHeight: "100vh",
        }}
      >
        <PrimeReactProvider>
          <UserAuthProvider>
            <MusicPlayerProvider>
              <Header />

              <div className="flex-grow-1">{children}</div>

              <Player />
              <BootstrapClient />
              <ToastContainer />
            </MusicPlayerProvider>
          </UserAuthProvider>
        </PrimeReactProvider>
      </body>
    </html>
  );
}
